#!/bin/sh

# Set these paths appropriately

BIN=/home/noname/workspace/qa.qcri.qf.pipeline/tools/treetagger/bin
CMD=/home/noname/workspace/qa.qcri.qf.pipeline/tools/treetagger/cmd
LIB=/home/noname/workspace/qa.qcri.qf.pipeline/tools/treetagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
