#!/bin/sh

# Set these paths appropriately

BIN=/home/noname/workspace/qa.qcri.qf.pipeline/tools/treetagger/bin
CMD=/home/noname/workspace/qa.qcri.qf.pipeline/tools/treetagger/cmd
LIB=/home/noname/workspace/qa.qcri.qf.pipeline/tools/treetagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovak-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
