#!/bin/sh

# Set these paths appropriately

BIN=/home/noname/workspace/qa.qcri.qf.pipeline/tools/treetagger/bin
CMD=/home/noname/workspace/qa.qcri.qf.pipeline/tools/treetagger/cmd
LIB=/home/noname/workspace/qa.qcri.qf.pipeline/tools/treetagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/italian-abbreviations
PARFILE=${LIB}/italian.par

$TOKENIZER -i -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
